services:

  frontend:
    image: frontend
    build: ./example-frontend/
    ports:
      - 127.0.0.1:5000:5000
      
  backend:
    image: backend
    build: ./example-backend/
    ports:
      - 127.0.0.1:8080:8080
      
  redis:
    image: redis:7-alpine
    restart: unless-stopped
