FROM node:16-slim

WORKDIR /usr/src/app

EXPOSE 5000

COPY . .

RUN npm install

RUN npm install -g serve

RUN REACT_APP_BACKEND_URL="http://localhost:8080" npm run build

CMD ["serve", "-s", "-p", "5000", "build"]
